name: flashchat
description: An Online Chatroom

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_analytics: ^10.8.0
  font_awesome_flutter: ^10.6.0
  shared_preferences: ^2.2.2
  animated_text_kit: ^4.2.2
  auto_size_text: ^3.0.0
  url_strategy: ^0.2.0
  google_fonts: ^6.1.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - "assets/images/"
